services:
  moontv-kvrocks:
    image: apache/kvrocks:2.15.0
    restart: always
    container_name: ${CONTAINER_NAME}
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:6666
    volumes:
      - ./data:/var/lib/kvrocks
    environment:
      - TZ=${TIME_ZONE}
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
