services:
  opengist:
    image: ghcr.io/thomiceli/opengist:1.12.1
    container_name: ${CONTAINER_NAME}
    networks:               
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:6157"
    environment:
      - TZ=${TIME_ZONE}
    volumes:
      - ./data:/opengist
    labels:                                   
      createdBy: "Apps"                       
networks:
  1panel-network:
    external: true
